### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PhillipSz** [PhillipSz/translationcheck#3]
- [ ] maybe use "systemd-cat -t translationcheck" for errors? We maybe not always have systemd!
- [ ] fix output, by not echoing dirctly, but instead save to array? use python!
- [ ] does ci work with gitlab?/ maybe just don't use declare -n ?
- [ ] Why does it sometimes hang, but works if I wait a bit? Only happens on the first run? Do we need to exit somewhere? I think python is the answer here :)

**Comment by PhillipSz** [comment]
I'm closing this as branch dev with e47f571 fixes all this.
